### PR TITLE
enh[android-2284] Unify S3 stubs and S3 fork

### PR DESCRIPTION
**Pull request by amccaleb**
See this commit onward for details relevant to Cognoa: https://github.com/cognoa/aws-sdk-android/commit/f47038ecce5c8e47867f9b3b5fed72638cc5baa8

### CODE REVIEW

**Comment by briancordanyoung** [comment]
@magjoh I've tried to view only that commits forward, but Github returns with this
Screen Shot 2022-05-17 at 11 20 16 AM

I'll try looking at each commit.

**Review by briancordanyoung — APPROVED** [review]
Well, that took some effort to get Chrome and Github to give me what I needed.  The best I could see, the only functional change for the Cognoa app code is the fix below.  All other changes are to addd comments to the AWS functions and the merge of the AWS library changes.

### TransferUtility.java: `getTransferRecord(int id)`

```java
TransferRecord transfer = updater.getTransfer(id);
if (transfer == null) {
	transfer = dbUtil.getTransferById(id);
	if (transfer == null) {
		LOGGER.error("Cannot find transfer with id: " + id);
		return null;
	}
}
return transfer;
```

Approving based on this.  Let me know if I seem to have missed something important!

**Comment by magjoh** [comment]
> @magjoh I've tried to view only that commits forward, but Github returns with this Screen Shot 2022-05-17 at 11 20 16 AM
> 
> I'll try looking at each commit.

I think it's because there are so many files updated that Github can't keep up. I did not force-push anything.

**Comment by magjoh** [comment]
> Well, that took some effort to get Chrome and Github to give me what I needed. The best I could see, the only functional change for the Cognoa app code is the fix below. All other changes are to addd comments to the AWS functions and the merge of the AWS library changes.
> 
> ### TransferUtility.java: `getTransferRecord(int id)`
> ```java
> TransferRecord transfer = updater.getTransfer(id);
> if (transfer == null) {
> 	transfer = dbUtil.getTransferById(id);
> 	if (transfer == null) {
> 		LOGGER.error("Cannot find transfer with id: " + id);
> 		return null;
> 	}
> }
> return transfer;
> ```
> 
> Approving based on this. Let me know if I seem to have missed something important!

I think there are a few other modifications when building the test version of the SDK (where all network calls are stubbed out), but that brings us to my dilemma, should I merge this to master or keep our changes in a separate branch and rebase it on top of master for every version update from the upstream? The way this PR is, it is impossible to find what we've modified vs what came from the upstream repository.

You are right that the highlighted code above is the main bug-fix enabling us to resume uploads properly.

**Comment by briancordanyoung** [comment]
>  should I merge this to master or keep our changes in a separate branch and rebase it on top of master for every version update from the upstream?

I can't say I understand enough about the two options to give you confidant input.  The thing that I'm focused on is that most of this PR is from a 3rd party dependency? Why is it in the Android app repo? Is there a way to keep this in a separate repo and include it like other 3rd party dependancies?

**Comment by magjoh** [comment]
> > should I merge this to master or keep our changes in a separate branch and rebase it on top of master for every version update from the upstream?
> 
> I can't say I understand enough about the two options to give you confidant input. The thing that I'm focused on is that most of this PR is from a 3rd party dependency? Why is it in the Android app repo? Is there a way to keep this in a separate repo and include it like other 3rd party dependancies?

It's not in the Android app repo, the compiled binaries from this repo are copied over to the `/libs/` folder in the Android app repo.
See https://github.com/cognoa/cognoa-android/issues/2146

**Comment by briancordanyoung** [comment]
> It's not in the Android app repo, the compiled binaries from this repo are copied over to the `/libs/` folder in the Android app repo.

LOL.  I completely missed that this is in `cognoa/aws-sdk-android` 🤦‍♂️

OK.   Well, I would do anything that you can to separate the merge from the origin repo and the changes specific to Cognoa in to two separate PRs.

**Comment by magjoh** [comment]
This PR is superseded by cognoa/aws-sdk-android#6

**Pull request closed without merging**
